[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.8"
sqlalchemy = "^2.0.35"
asyncpg = "^0.29.0"
pydantic-settings = "^2.5.2"
cachetools = "^5.5.0"
aiogram = "^3.13.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
